<a href="https://colab.research.google.com/github/HUSSAIN7860/Python_EyTraining/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### import necessary library

In [ ]:
import numpy as np

import random

In [ ]:
# taking at random 6 people age
ages = random.sample(range(10, 30), 6)

print(ages)

[26, 24, 10, 28, 20, 27]


### There are three ways to initiate the ndarray like np.array(<collection>)

In [ ]:
ages = np.array(ages)
print(type(ages),ages)

<class 'numpy.ndarray'> [26 24 10 28 20 27]


In [ ]:
print(ages.shape , ages.size)

(6,) 6


In [ ]:
a = np.array([[26, 24 ,10 ,28 ,20, 27 ,1],[2,4,5,9,7,8,1]])
print(a.shape , a.size)

(2, 7) 14


In [ ]:
# creating array having all element is 0
zeroArr = np.zeros(5)
zeroArrnd = np.zeros([5,2])
print(zeroArrnd ,'->', zeroArr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] -> [0. 0. 0. 0. 0.]


### Multi-Dimentions

In [ ]:
weight = random.sample(range(40,70),6)
print(weight)

[57, 60, 59, 48, 54, 47]


In [ ]:
# assign the weight to the ages and print the shape and size of it 
people= np.array([ages,weight])

print('The array is ',people ,'the shape of the people ', people.shape , 'and the  size of the array',people.size)

The array is  [[26 24 10 28 20 27]
 [57 60 59 48 54 47]] the shape of the people  (2, 6) and the  size of the array 12


In [ ]:
# you can take any possible product rows and colounm and whose product is always equal to shape of the ARRAY  

people = people.reshape(3,4)
print(f'the array is {people} shape {people.shape} and the size is {people.size}')

the array is [[26 24 10 28]
 [20 27 57 60]
 [59 48 54 47]] shape (3, 4) and the size is 12


### Exercise
Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

Generate a matrix (2D numpy array) of the values:

 
 
Change the dimensions of this array to another permitted shape


In [ ]:
# 1. 
a = [7, 9, 65, 33, 85, 99]
array = np.array(a)
print(array)
print(array.shape , array.size)

[ 7  9 65 33 85 99]
(6,) 6


In [ ]:
# 2.
first_row = [1,2,4]
second_row =[2,3,0]
third_row = [0,5,1]

matrix = np.array([first_row,second_row,third_row])
print(matrix)
print(matrix.shape , matrix.size , type(matrix))

[[1 2 4]
 [2 3 0]
 [0 5 1]]
(3, 3) 9 <class 'numpy.ndarray'>


In [ ]:
# 3.
matrix = matrix.reshape(1,9)
print(matrix)


[[1 2 4 2 3 0 0 5 1]]


### Array Generation 

In [ ]:
# with the help of numpy we can generate the array

six_times_space = np.arange(0,60,6)
# first argument takes the initial values and second takes the last value but exclusively 
# third step is step which it takes.
six_times_space

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

* The np.linspace() method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.

In [ ]:
table = np.linspace(1,20,12)
# gives you the 20 number and having difference between two number is equal here 
print(table)

[ 1.          2.72727273  4.45454545  6.18181818  7.90909091  9.63636364
 11.36363636 13.09090909 14.81818182 16.54545455 18.27272727 20.        ]


* The .repeat() method will repeat an object you pas a specified number of times.

In [ ]:
arr = np.repeat(2,10)
# first argument assign to second argument times
print(arr)

[2 2 2 2 2 2 2 2 2 2]


* The np.eye() functions will create an identity matrix/array for us.

In [ ]:
identity_mat = np.eye(5)
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Operations
 * We can perform many operation on the array . few  are below 

In [ ]:
# performing BODMAS 
print(six_times_space)

print('exponent operation performing ', six_times_space**2)
print('addition operation performing ', six_times_space+10)
print('substraction operation performing ', six_times_space-5)
print('divion operation performing ', six_times_space/3)
print('multiplication operation performing ', six_times_space*8)

[ 0  6 12 18 24 30 36 42 48 54]
exponent operation performing  [   0   36  144  324  576  900 1296 1764 2304 2916]
addition operation performing  [10 16 22 28 34 40 46 52 58 64]
substraction operation performing  [-5  1  7 13 19 25 31 37 43 49]
divion operation performing  [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
multiplication operation performing  [  0  48  96 144 192 240 288 336 384 432]


### Speed test
* numpy perform faster operation than a traditional core python

In [ ]:
l = list(range(1 ,10000,5))
l

In [ ]:
l_np = np.arange(1,10000,5)
l_np

array([   1,    6,   11, ..., 9986, 9991, 9996])

In [ ]:
%timeit l_np*5

2.25 µs ± 40.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit [e*5  for e in l]

133 µs ± 780 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


* Boolean string operations can also be performed on ndarrays.

In [ ]:
animal = np.array(['elephant','lion','tiger','monkey'])
print(np.isin(animal,'i'))

print('i' in animal)
['i' in animal for animal in animal]


[False False False False]
False


[False, True, True, False]

### Transpose

In [ ]:
#
print(people , '\n')
people.shape = (2,6)

print(people , '\n')
print(people.T)


[[26 24 10 28]
 [20 27 57 60]
 [59 48 54 47]] 

[[26 24 10 28 20 27]
 [57 60 59 48 54 47]] 

[[26 57]
 [24 60]
 [10 59]
 [28 48]
 [20 54]
 [27 47]]


### Data Types
As previously mentioned, ndarrays can only have one data type. If we want to obtain or change this, we use the .dtype attribute

In [ ]:
people.dtype

dtype('int64')

What is the data type of the below ndarray?

In [ ]:
ages_with_string = [1,3,4,'23','20','19']
ages_with_string
type(ages_with_string)

list

What is the dtype of this array?

In [ ]:
ages_with_string = np.array([1,2,3,'23',20,'19'],dtype = 'int64')
ages_with_string.dtype

dtype('int64')

What do you think has happened here?

In [ ]:
ages_with_string = np.array([1,2,3,'23',20,'19'],dtype = 'int64') # every value of the array change into int64 types here 
print(ages_with_string)

[ 1  2  3 23 20 19]


In [ ]:
ages_with_string.dtype = 'int32' # if i change to int32 dtype then 0 comes at alternate position
print(ages_with_string)

[ 1  0  2  0  3  0 23  0 20  0 19  0]


In [ ]:
ages_with_string.size

12

In [ ]:
ages_with_string.size/12

1.0

In [ ]:
np.array([10, 5, 8, '32', '65', '43']).size

6

The correct way to have changed the data type of the ndarray would have been to use the .astype() method, demonstrated below

In [ ]:
# astype() change the data type 
ages_with_string = np.array([1,3,4,'23','20','19'])
print(ages_with_string)
print(ages_with_string.astype('int32'))

['1' '3' '4' '23' '20' '19']
[ 1  3  4 23 20 19]


### Exercise
#### Create an array of string numbers, but use dtype to make it an array of floats.
#### Transpose the matrix, printing the new size and shape.
#### Use the .astype() method to convert the array to boolean.

In [ ]:
# 1.
arr = ['22','2','19','15']
arr_float = np.array(arr,dtype='float')
arr_float.dtype

dtype('float64')

In [ ]:
# 2.
arr_float.shape = (2,2)
print(arr_float, '\n')
print(arr_float.T)

[[22.  2.]
 [19. 15.]] 

[[22. 19.]
 [ 2. 15.]]


In [ ]:
# 3.
print(arr_float.astype('bool'))

[[ True  True]
 [ True  True]]


### Array slicing Operations

> As before, we can use square brackets and indices to access individual values, and the colon operator to slice the array



In [ ]:
six_times_space[:]

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

In [ ]:
# printing first element 
print(six_times_space[0])
# printing first five number 
print(six_times_space[0:5])
# with step
print(six_times_space[::-1])

0
[ 0  6 12 18 24]
[54 48 42 36 30 24 18 12  6  0]




> we can also slice ndimention array



In [ ]:
print(people)
print(people[:2,:3])

[[26 24 10 28 20 27]
 [57 60 59 48 54 47]]
[[26 24 10]
 [57 60 59]]


### Exercise
Exercise
Create a numpy array with 50 zeros

Create a np array of 2 repeated 20 times

Create a numpy array from 0 to 2  in steps of 0.1

For one of the arrays generated:

Get the first five values

Get the last 3 values

Get the 4th value to the 7th value

In [ ]:
# 1 .
fifty_zeros = np.zeros(50)
print(fifty_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [ ]:
# 2.
two_repeat = np.repeat(2,20)
print(two_repeat)
print(len(two_repeat))

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
20


In [ ]:
# 3.
import math
step_arr = np.arange(0,2*math.pi,0.1)
step_arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [ ]:
# 4.
step_arr[:5]

array([0. , 0.1, 0.2, 0.3, 0.4])

In [ ]:
# 5.
step_arr[-3:]

array([6. , 6.1, 6.2])

In [ ]:
# 6.
step_arr[3:8]

array([0.3, 0.4, 0.5, 0.6, 0.7])

### We can reverse an array by using .flip() or by using the :: operator.

In [ ]:
reverse_table = np.flip(six_times_space)
print(reverse_table)

[54 48 42 36 30 24 18 12  6  0]


In [ ]:
reverse_table = reverse_table[::-1]
print(reverse_table)

[ 0  6 12 18 24 30 36 42 48 54]




> We can also use the :: operator to select steps of the original array



In [ ]:
print(reverse_table[::2])

[ 0 12 24 36 48]


### Exercise
Take one of the arrays you defined and

#### Reverse it
#### Only keep every 4th element.
#### Get every 2nd element, starting from the last and moving backwards.

In [ ]:
# 1.
print(reverse_table[::-1])

[54 48 42 36 30 24 18 12  6  0]


In [ ]:
# 2.
print(reverse_table[::4])

[ 0 24 48]


In [ ]:
# 3.
print(reverse_table[::-2])

[54 42 30 18  6]


### Stats

In [ ]:
# using round funtion 
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [ ]:
num = np.arange(1,10,0.353)
num

array([1.   , 1.353, 1.706, 2.059, 2.412, 2.765, 3.118, 3.471, 3.824,
       4.177, 4.53 , 4.883, 5.236, 5.589, 5.942, 6.295, 6.648, 7.001,
       7.354, 7.707, 8.06 , 8.413, 8.766, 9.119, 9.472, 9.825])

### Exercise
Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [ ]:
print("min = ", np.min(num).round(2))
print("max = ", np.max(num).round(2))
print("sum = ", np.sum(num).round(2))
print("mean = ", np.mean(num).round(2))
print("median = ", np.median(num).round(2))
print("var = ", np.var(num).round(2))
print("std = ", np.std(num).round(2))

min =  1.0
max =  9.82
sum =  140.72
mean =  5.41
median =  5.41
var =  7.01
std =  2.65


### Random
With np.random, we can generate a number of types of dataset, and create training data.

The below code simulates a fair coin toss.

In [ ]:
toss = np.random.choice([0,1],10)
toss

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 1])

In [ ]:
#Random With np.random, we can generate a number of types of dataset, and create training data.


np.random.rand(2,5,3)

array([[[0.36942379, 0.48116474, 0.88967326],
        [0.06563901, 0.90052295, 0.18953549],
        [0.94258741, 0.45224683, 0.12233642],
        [0.69518442, 0.57500214, 0.86124759],
        [0.32731683, 0.26218071, 0.2894768 ]],

       [[0.60719407, 0.48141691, 0.8205382 ],
        [0.85901616, 0.47086724, 0.14782527],
        [0.79300468, 0.86324179, 0.62092897],
        [0.39027145, 0.07556635, 0.36720905],
        [0.84689016, 0.36236792, 0.56275124]]])



> We can produce 1000 datapoints of a normally distributed data set by using np.random.normal()



In [ ]:
mu , sigma = 0 , 0.1 # mu is mean and sigma is standard deviation here 
np.random.normal(mu,sigma,20) # 20 data points which normal distribution

array([ 0.01719333,  0.06350111,  0.04972689, -0.10228559, -0.02342303,
        0.04590006, -0.02223842, -0.02721601,  0.02188397, -0.18729414,
        0.00753161, -0.08895092,  0.0405058 ,  0.15304926,  0.11338763,
       -0.06232181,  0.05762666, -0.11265081, -0.03502566,  0.14712911])

### Exercise
Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.

Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.

In [ ]:
# 1.
np.random.choice([x for x in range(0,7)],10)

array([4, 3, 1, 5, 6, 2, 6, 4, 6, 3])

In [ ]:
# 2. for Head = 1 , for tails = 0
toss = np.random.choice([0,1,1],10)
print(toss)


[0 0 0 1 1 1 1 1 0 1]
